### ISSUE TITLE
PATH issuse with pyprophet

### ISSUE THREAD

**Issue by sjr24** [PyProphet/pyprophet#33]
Greetings,
#cmd prompt was set to directory with .osw files.  The following command was run

C:\Users\Shawn\Desktop\DIA2018\Tutorial4_OpenSWATH>pyprophet merge --out=training.osw --subsample_ratio=0.33 *.osw

#The error listed below was produced by the above command.

Usage: pyprophet merge [OPTIONS] [INFILES]...

Error: Invalid value for "infiles": Path "*.osw" does not exist.

Adding the path the command "C:\Users\Shawn\Desktop\DIA2018\Tutorial4_OpenSWATH\*.osw" did not work either.

Any suggestions?

Thanks,
Shawn

**Comment by grosenberger** [comment]
I'm unfortunately not sure about wildcards on Windows and there might be differences between the command line and PowerShell. Does it work if you use the full filenames?

**Comment by sjr24** [comment]
George,
Using the full file names allowed the files to be recognized, but the following error occurred.  This error occurred in Power Shell and the Command prompt.

PS C:\Users\srice\Desktop\DIA2018\Tutorial4_OpenSWATH> C:\Anaconda3\Scripts\pyprophet merge --out=training.osw --subsample_ratio=0.33 collinsb_I180316_001_SW-A.osw collinsb_I180316_002_SW-B.osw
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\pyprophet.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\pyprophet\main.py", line 191, in merge
    merge_osw(infiles, outfile, subsample_ratio, test)
  File "c:\anaconda3\lib\site-packages\pyprophet\levels_contexts.py", line 217, in merge_osw
    ''')
sqlite3.OperationalError: no such table: RUN

Any ideas?

Thanks,
Shawn

**Comment by grosenberger** [comment]
Hi Shawn,

Are you using OpenSWATH 2.3? This version unfortunately is not yet fully compatible with the new PyProphet. Version 2.4 will be released over the next few weeks or you could also use the development version or nightly builds. On Windows, it might be a better to use the Docker image that we provide which contains all compatible versions of the tools.

**Comment by sjr24** [comment]
George,
I am, indeed, using OpenSWATH v2.3.  I will play around with the docker.

Thanks,
Shawn

**Comment by JeBu42** [comment]
Hi George,

I hope this is the correct place to post the following, and apologies Shawn if you have since sorted this and moved on. 
I was having the same issue (before realising PyProphet wasn't supported by OpenMS 2.3), and have since decided to install the latest OpenMS nightly version. 
However, when running PyProphet this time, I now get the following (in Command prompt and Power Shell):

C:\Jess\OpenSWATH\CAF\v42>pyprophet merge --out=training.osw --subsample_ratio=0
.33 20180727_SWATH_CAFref_HpH*.osw

usage:
       pyprophet [options] input_file
   or
       pyprophet --help
   or
       pyprophet --version

parameters:

    --apply_scorer                               default: None  [name of *_score
r.bin file of existing classifier]
    --apply_weights                              default: None  [name of *_weigh
ts.txt file of existing LDA weights]
    --compute.probabilities                      default: False [Compute approxi
mate binned probability values]
    --d_score.cutoff                             default: -1000.0 [Filter output
 such that only results with a d_score higher than this value are reported]
    --delim.in                                   default: 'tab' [you can eg use
'tab' or ',']
    --delim.out                                  default: 'tab' [you can eg use
'tab' or ',']
    --export.mayu                                default: False [export input fi
les for MAYU]
    --final_statistics.fdr_all_pg                default: False [use all peak gr
oups for score & q-value calculation]
    --final_statistics.lambda                    default: 0.4
    --ignore.invalid_score_columns               default: False [ignore score co
lumns which only contain NaN or infinity values]
    --is_test                                    default: 0     [switches random
ness off]
    --num_processes                              default: 1     [-1 means 'all a
vailable cpus']
    --semi_supervised_learner.initial_fdr        default: 0.15
    --semi_supervised_learner.initial_lambda     default: 0.4
    --semi_supervised_learner.iteration_fdr      default: 0.02
    --semi_supervised_learner.iteration_lambda   default: 0.4
    --semi_supervised_learner.num_iter           default: 5
    --target.dir                                 default: None
    --target.overwrite                           default: 0
    --xeval.fraction                             default: 0.5
    --xeval.num_iter                             default: 5

Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\runpy.py", line 174, in _run_module_as_main

    "__main__", fname, loader, pkg_name)
  File "c:\programdata\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Anaconda2\Scripts\pyprophet.exe\__main__.py", line 9, in
<module>
  File "c:\programdata\anaconda2\lib\site-packages\pyprophet\main.py", line 61,
in main
    _main(sys.argv[1:])
  File "c:\programdata\anaconda2\lib\site-packages\pyprophet\main.py", line 87,
in _main
    raise Exception("duplicate input file argument")
Exception: duplicate input file argument


Any advise would be greatly appreciated!
If not, as you've recommended above, I will have a go with Docker, but thought it was worth asking about this anyway!

Best,
Jess

**Comment by grosenberger** [comment]
Hi Jess,

It seems that you are using the latest version of PyProphet on PyPI. The commands only work with the GitHub version at the moment though. 

OpenMS 2.4 was released a few days ago and I will release a compatible PyProphet version (same as current GitHub version) on PyPI within the next days.

Best regards,
George

**Comment by grosenberger** [comment]
Ok, PyProphet 2.0.1 is now available from PyPI: https://pypi.org/project/pyprophet/2.0.1/

This version should be fully compatible with OpenMS 2.4: https://github.com/OpenMS/OpenMS/releases/tag/Release2.4.0

**Comment by JeBu42** [comment]
Great! Thanks so much for the quick reply - I look forward to trying it out.
Jess
